# Config file for automatic testing at travis-ci.org
language: python
cache: pip

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# test script
script: tox

matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.8
      env: TOXENV=flake8
    - python: 3.8
      env: TOXENV=build
    - python: 3.8
      env: TOXENV=readme
