global:
  vcloud:
    hostname: vcdservername
    username: login
    password: "********"
    api_version: "33.0"
    ssl_verify: yes
    cache_timeout: 300
  log:
    config_file: logging.json
  amqp:
    host: amqpservername
    port: 5671
    ssl: yes
    vhost: "%2F" # == /
    username: login
    password: "********"
  max_thread: 50


extensions:
  example1:
    backend:
      endpoint: http://127.0.0.1:8881
      uri_replace:
        pattern: /api/example1/
        by: ''
      ssl_verify: no
      forward_rights: yes
      auth: # basic auth
        username: rest_username
        password: "********"
      timeout: 30
    amqp:
      routing_key: example1
      exchange:
        name: defaultExchange
        type: direct
        durable: yes
      queue:
        name: example1
        message_ttl: 40000
      declare: no
    vcloud:
      api_extension:
        namespace: example1
        exchange: ExchangeTest1
        routing_key: example1
        api_filters:
          - '/api/example1/test/.*'
        force_redeploy: no
      validate_org_membership: yes
      reference_right: "UI Plugins: View"
  example2:
    backend:
      endpoint: http://127.0.0.1:8882
      uri_replace:
        pattern: /api/example1/
        by: ''
      ssl_verify: no
      forward_rights: no
      auth: # basic auth
        username: rest_username
        password: "********"
      timeout: 10
    amqp:
      routing_key: example2
      exchange:
        name: defaultExchange
      queue:
        name: example2
        message_ttl: 40
      declare: no
    vcloud:
      api_extension:
        namespace: example2
        exchange: ExchangeTest2
        routing_key: example2
        api_filters:
          - '/api/this/is/1/test/example2/.*/.*'
        force_redeploy: yes
      validate_org_membership: yes
      reference_right: no
