global:
  vcloud:
    hostname: vcdservername
    username: login
    password: "********"
    api_version: 31
  log:
    config_file: logging.json
  amqp:
    host: amqpservername
    port: 5671
    ssl: yes
    vhost: "%2F" # == /
    username: login
    password: "********"
  max_thread: 50


extensions:
  example1:
    backend:
      endpoint: http://127.0.0.1:8881
      uri_replace:
        pattern: /api/example1/
        by: ''
      ssl_verify: no
      forward_rights: yes
      auth: # basic auth
        username: rest_username
        password: "********"
      timeout: 30
    amqp:
      routing_key: example1
      exchange:
        name: defaultExchange
        type: direct
        durable: yes
      queue:
        name: example1
        message_ttl: 40000
      declare: no
    validate_org_membership: yes
    reference_right: "UI Plugins: View"
  example2:
    backend:
      endpoint: http://127.0.0.1:8882
      uri_replace:
        pattern: /api/example1/
        by: ''
      ssl_verify: no
      forward_rights: no
      auth: # basic auth
        username: rest_username
        password: "********"
      timeout: 10
    amqp:
      routing_key: example2
      exchange:
        name: defaultExchange
      queue:
        name: example2
        message_ttl: 40
      declare: no
    validate_org_membership: yes
    reference_right: no
